"""Add missing fields to Memory model

Revision ID: 618c51757f22
Revises: e3704b220fd3
Create Date: 2025-10-01 18:21:31.539030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618c51757f22'
down_revision: Union[str, Sequence[str], None] = 'e3704b220fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('memories', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('memories', sa.Column('content_hash', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_memories_content_hash'), 'memories', ['content_hash'], unique=False)
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_foreign_key(None, 'memories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_content_hash'), table_name='memories')
    op.drop_column('memories', 'content_hash')
    op.drop_column('memories', 'title')
    op.drop_column('memories', 'user_id')
    # ### end Alembic commands ###
