"""Revert Memory model to match original ERD

Revision ID: 694a99143351
Revises: 618c51757f22
Create Date: 2025-10-01 18:24:01.162958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694a99143351'
down_revision: Union[str, Sequence[str], None] = '618c51757f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memories_content_hash'), table_name='memories')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_constraint(op.f('memories_user_id_fkey'), 'memories', type_='foreignkey')
    op.drop_column('memories', 'content_hash')
    op.drop_column('memories', 'title')
    op.drop_column('memories', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('memories', sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('memories', sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('memories_user_id_fkey'), 'memories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_index(op.f('ix_memories_content_hash'), 'memories', ['content_hash'], unique=False)
    # ### end Alembic commands ###
